Merge req for DESeq2 module
icbi-lab/nf-deseq2 pull request #20
Opened 2021-11-24 15:26 UTC by sandrocarollo

2021-12-06 21:02 UTC, grst reviewed
Thanks for adding this so quickly :) 

I added a few comments, some of which are related to issues that probably already existed in the original R script.

2021-12-06 21:02 UTC, grst commented on modules/DESeq2.nf
>  	conda "conda-forge::python=3.8"
Could you please add all required R packages here?

2021-12-06 21:02 UTC, grst commented on modules/DESeq2.nf
> +        path p1
```suggestion
    path p1
```

2021-12-06 21:02 UTC, grst commented on modules/DESeq2.nf
> +    Rscript $projectDir/DESeq2_script.R $p1 $p2 --wdir `echo \$PWD` > DESeq2_result.txt
This will likely fail when using docker, since the projectDir might not get mounted into the container. 

The best way to solve this is to put the script in the `bin` directory, make it executable with `chmod +x` and call it like this
```
"""
DESeq2_script.R $p1 [...]
"""
```

2021-12-06 21:02 UTC, grst commented on modules/DESeq2.nf
> +        path p1
Please use a more descriptive variable name than `p1`.

2021-12-06 21:02 UTC, grst commented on modules/DESeq2.nf
> +    Rscript $projectDir/DESeq2_script.R $p1 $p2 --wdir `echo \$PWD` > DESeq2_result.txt
Also `echo \$PWD` shouldn't be required, you can just use `.` as working directory.

2021-12-06 21:02 UTC, grst commented on modules/nextflow.config
> +}
Great to have this all as params :) 
This will probably go to a global `nextflow.config` file, but that's something we need to figure out once a few more modules are added. So let's leave it for now!

2021-12-06 21:02 UTC, grst commented on modules/DESeq2_script.R
> +p <- add_argument(p, "--resDir", help="Output result directory", default="./results")
what's the difference between `resDir` and `wdir`?

2021-12-06 21:02 UTC, grst commented on modules/DESeq2_script.R
> +p <- add_argument(p, "--fdr", help="False discovery rate for GO analysis and volcano plots", default=0.1)
Do we even need the FDR in this step already?

2021-12-06 21:02 UTC, grst commented on modules/DESeq2_script.R
> +sample_col <- "sample"
This overrides `sample_col` independent of the specified parameter

2021-12-06 21:02 UTC, grst commented on modules/DESeq2_script.R
> +n_cpus <- 8
Best to pass nextflow's `task.cpus` to `MulticoreParam`

2021-12-06 21:02 UTC, grst commented on modules/DESeq2_script.R
> +nc <- counts(dds, normalized=T)
this isn't used anywhere?

2021-12-06 21:02 UTC, grst commented on modules/DESeq2_script.R
> +  arrange(pvalue)
This is the main result of the script and should be stored as tsv?

2021-12-14 08:49 UTC, grst commented
@sandrocarollo, I implemented a demo process that consumes the samplesheet and gene expression matrix. 
You can add the DESeq2 process to the main workflow in the same way and it should get tested automatically using [these test data](https://github.com/icbi-lab/nf-deseq2/tree/19ccb77a88c184aba2b322b39cad0474ab7465b3/tests/testdata/example_clean). 

https://github.com/icbi-lab/nf-deseq2/blob/19ccb77a88c184aba2b322b39cad0474ab7465b3/main.nf#L7-L15

2021-12-22 14:31 UTC, sandrocarollo commented on modules/DESeq2.nf
> +    Rscript $projectDir/DESeq2_script.R $p1 $p2 --wdir `echo \$PWD` > DESeq2_result.txt
Really clever, I didn't think about it, thanks! :)

2021-12-22 14:32 UTC, sandrocarollo commented on modules/DESeq2_script.R
> +p <- add_argument(p, "--resDir", help="Output result directory", default="./results")
I removed wdir, and substituted with just `"."`

2021-12-22 14:33 UTC, sandrocarollo commented on modules/DESeq2_script.R
> +p <- add_argument(p, "--fdr", help="False discovery rate for GO analysis and volcano plots", default=0.1)
Yes, it's used in the last line of the code. But it's a simple print so it can be also removed if not strictly necessary!

2021-12-22 14:34 UTC, sandrocarollo commented on modules/DESeq2_script.R
> +  arrange(pvalue)
Yes you're right, I added to the output files!

2021-12-23 09:13 UTC, grst requested changes
Looks great now! There is just the conda issue we already discussed, and I think it makes sense now to integrate the DESeq2 process into the main pipeline.

2021-12-23 09:13 UTC, grst commented on modules/DESeq2.nf
> +        conda "conda-forge::r-argparser=0.7.1"
as discussed yesterday, this needs to be merged into a single line to work.

2021-12-23 09:13 UTC, grst commented on modules/DESeq2.nf
> +}
With the input channel handling now implemented in `main.nf`, you could add the `DESeq2` call to the main pipeline! 

I figured this is also the reason why the script could not be found: The bin dir is always relative to the nextflow script that is being executed, the `bin` dir is `../` from here.

2021-12-23 09:13 UTC, grst commented on modules/nextflow.config
> +params {
Could you please merge this file with the main `nextflow.config` at the root of this repository?

2022-01-20 07:36 UTC, grst commented
This seems to have done the trick! 
There were two problems: 
 * the CI server only has 8GB ram and 2 CPUs. The pipeline failed because it requested more. 
 * Since you modified the input files, the output of `dummyCheckInput` has changed, which was checked by the CI, so this was expected.

2022-01-20 09:26 UTC, grst approved these changes
ok. let's go!

2022-01-20 09:26 UTC, merged